
services:
  database:
    container_name: starticoins_database
    image: postgres:alpine
    environment:
      - POSTGRES_USER=starticoins
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=starticoins
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: starticoins_redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379:6379"
    env_file: .env
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
